41 | Mechanical Properties | The ratio of load to original cross-sectional area is called | engineering stress | true stress | engineering strain | true strain | A | engineering stress | Medium | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
42 | Mechanical Properties | The ratio of load to instantaneous cross-sectional area is called | engineering stress | true stress | engineering strain | true strain | B | true stress | Medium | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
43 | Mechanical Properties | The ratio of change in length to original length is called | engineering stress | true stress | engineering strain | true strain | C | engineering strain | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
44 | Mechanical Properties | The ratio of change in length to instantaneous length is called | engineering stress | true stress | engineering strain | true strain | D | true strain | Medium | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
45 | Mechanical Properties | The maximum stress a material can withstand without permanent deformation is called | yield strength | ultimate tensile strength | fracture strength | elastic limit | A | yield strength | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
46 | Mechanical Properties | The maximum stress a material can withstand is called | yield strength | ultimate tensile strength | fracture strength | elastic limit | B | ultimate tensile strength | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
47 | Mechanical Properties | The stress at which fracture occurs is called | yield strength | ultimate tensile strength | fracture strength | elastic limit | C | fracture strength | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
48 | Mechanical Properties | The stress below which no plastic deformation occurs is called | yield strength | ultimate tensile strength | fracture strength | elastic limit | D | elastic limit | Medium | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
49 | Mechanical Properties | The ability of a material to absorb energy before fracture is called | toughness | hardness | ductility | strength | A | toughness | Medium | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
50 | Mechanical Properties | The resistance of a material to indentation or scratching is called | toughness | hardness | ductility | strength | B | hardness | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
51 | Mechanical Properties | The ability of a material to undergo plastic deformation without fracture is called | toughness | hardness | ductility | strength | C | ductility | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
52 | Mechanical Properties | The ability of a material to withstand load without deformation is called | toughness | hardness | ductility | strength | D | strength | Easy | 1_Mechanical Property of Materials_ABL[RE] 1_2568.pdf
53 | Steelmaking | The basic oxygen furnace is used for | producing pig iron | converting pig iron to steel | casting steel | refining steel | B | converting pig iron to steel | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
54 | Steelmaking | The electric arc furnace is used for | producing pig iron | converting pig iron to steel | recycling scrap steel | refining steel | C | recycling scrap steel | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
55 | Steelmaking | Limestone is added in the blast furnace as a | fuel | reducing agent | flux | oxidizing agent | C | flux | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
56 | Steelmaking | Coke is used in the blast furnace as a | fuel | reducing agent | both fuel and reducing agent | flux | C | both fuel and reducing agent | Easy | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
57 | Cast Irons | White cast iron has | graphite flakes | nodular graphite | cementite | no carbon | C | cementite | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
58 | Cast Irons | Malleable cast iron is produced by | heat treatment of white cast iron | adding magnesium to molten iron | slow cooling | rapid cooling | A | heat treatment of white cast iron | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
59 | Cast Irons | Nodular cast iron is produced by | heat treatment | adding magnesium to molten iron | slow cooling | rapid cooling | B | adding magnesium to molten iron | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
60 | Cast Irons | Gray cast iron has good | machinability | ductility | toughness | weldability | A | machinability | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
61 | Corrosion | Galvanic corrosion occurs when | two dissimilar metals are in electrical contact in an electrolyte | a metal is exposed to oxygen | a metal is exposed to water | a metal is exposed to acid | A | two dissimilar metals are in electrical contact in an electrolyte | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
62 | Corrosion | Pitting corrosion is a form of | uniform corrosion | localized corrosion | galvanic corrosion | crevice corrosion | B | localized corrosion | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
63 | Corrosion | The process of coating steel with zinc is called | galvanizing | anodizing | tinning | electroplating | A | galvanizing | Easy | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
64 | Corrosion | The process of coating steel with tin is called | galvanizing | anodizing | tinning | electroplating | C | tinning | Easy | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
65 | Corrosion | The process of forming a protective oxide layer on aluminum is called | galvanizing | anodizing | tinning | electroplating | B | anodizing | Medium | 4 SteelMakingTypeCastIronsCorrosion_MaterialsManu_1_68.pdf
66 | Polymer | Thermoplastic polymers can be | melted and reshaped | not melted after curing | cross-linked | vulcanized | A | melted and reshaped | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
67 | Polymer | Thermosetting polymers can be | melted and reshaped | not melted after curing | easily recycled | remolded | B | not melted after curing | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
68 | Polymer | The process of adding sulfur to rubber is called | vulcanization | polymerization | cross-linking | curing | A | vulcanization | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
69 | Polymer | The process of joining monomers to form a polymer is called | vulcanization | polymerization | cross-linking | curing | B | polymerization | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
70 | Composites | The matrix in a composite material | holds the reinforcement together | provides strength | provides stiffness | is always a metal | A | holds the reinforcement together | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
71 | Composites | The reinforcement in a composite material | provides strength and stiffness | holds the matrix together | is always a polymer | is always a ceramic | A | provides strength and stiffness | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
72 | Composites | A composite with fibers aligned in one direction has | high strength in the fiber direction | high strength in all directions | isotropic properties | high toughness in all directions | A | high strength in the fiber direction | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
73 | Composites | A composite with randomly oriented fibers has | high strength in the fiber direction | isotropic properties | anisotropic properties | high toughness in one direction | B | isotropic properties | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
74 | Ceramics | Advanced ceramics are based on | clay | silica | alumina | zirconia | C | alumina | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
75 | Ceramics | Ceramics are typically | ductile | brittle | tough | malleable | B | brittle | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
76 | Ceramics | Ceramics have high | electrical conductivity | thermal conductivity | melting point | ductility | C | melting point | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
77 | Ceramics | Ceramics are good | electrical conductors | thermal conductors | insulators | magnetic materials | C | insulators | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
78 | Powder Metallurgy | The first step in powder metallurgy is | mixing | compacting | sintering | powder production | D | powder production | Medium | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
79 | Powder Metallurgy | The process of mixing metal powders with lubricants is called | blending | compacting | sintering | powder production | A | blending | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf
80 | Powder Metallurgy | The process of pressing metal powders into a die is called | blending | compacting | sintering | powder production | B | compacting | Easy | 6 Polymer Composites powder metallurgy and ceramic EN 68.pdf